# Generated by Django 5.2.2 on 2025-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('P', 'Producer'), ('N', 'Normal'), ('S', 'Seller')], default='N', max_length=1, null=True),
        ),
    ]
