# Generated by Django 5.2.2 on 2025-06-12 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'خریدار معمولی'), (2, 'تولیدکننده'), (3, 'فروشنده')], default='N', null=True),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cc03745e-e4d7-46b0-bd08-3b86091a80bb'), primary_key=True, serialize=False)),
                ('code_type', models.IntegerField(choices=[(1, 'ثبت نام')])),
                ('code', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
