# Generated by Django 4.2.23 on 2025-06-15 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_verification_code_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'خریدار معمولی'), (2, 'تولیدکننده'), (3, 'فروشنده')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code_type',
            field=models.IntegerField(choices=[(1, 'ثبت نام'), (2, 'ورود یکبار مصرف'), (3, 'بازیابی رمز عبور'), (4, 'تغییر شماره تلفن')]),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
