# Generated by Django 5.2.2 on 2025-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_verificationcode_expires_at_verificationcode_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'خریدار معمولی'), (2, 'تولیدکننده'), (3, 'فروشنده'), (4, 'ادمین'), (5, 'بازاریاب')], default=1, null=True),
        ),
    ]
