# Generated by Django 5.2.2 on 2025-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'خریدار معمولی'), (2, 'تولیدکننده'), (3, 'فروشنده')], default=1, null=True),
        ),
    ]
