# Generated by Django 5.2.2 on 2025-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code_type',
            field=models.IntegerField(choices=[(1, 'ثبت نام'), (2, 'ورود یکبار مصرف'), (3, 'بازیابی رمز عبور'), (4, 'تغییر شماره تلفن'), (5, 'ثبت نام دوباره کاربر')]),
        ),
    ]
