# Generated by Django 4.2.23 on 2025-06-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر دسته بندی')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'db_table': '',
                'ordering': ['parent__id', 'position'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('minimum_order', models.PositiveIntegerField(default=1, verbose_name='حداقل میزان سفارس')),
                ('product_type', models.IntegerField(choices=[(1, 'عمده'), (2, 'خرده')], default=1, verbose_name='نوع محصول')),
                ('base_price', models.PositiveIntegerField(verbose_name='قیمت  ')),
                ('status', models.IntegerField(choices=[(1, 'موجود'), (2, 'ناموجود')], default=1, verbose_name='وضعیت محصول')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی در انبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='دسته\u200cبندی')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional_images/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='متن جایگزین تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='product_pro_status_48d769_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='product_cat_status_2db3d1_idx'),
        ),
    ]
