# Generated by Django 4.2.23 on 2025-06-28 09:47

from django.db import migrations, models
import utils.imageuploader


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=utils.imageuploader.upload_product_image, verbose_name='تصویر'),
        ),
    ]
