# Generated by Django 5.2.2 on 2025-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_base_price_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default='ab', max_length=100, verbose_name='یونیکد زیرشاخه'),
            preserve_default=False,
        ),
    ]
