# Generated by Django 5.2.2 on 2025-07-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=100, verbose_name='یونیکد زیرشاخه'),
        ),
    ]
