# Generated by Django 5.2.2 on 2025-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_parent_alter_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'عمده'), (2, 'خرده')], default=2, verbose_name='نوع محصول'),
        ),
    ]
