# Generated by Django 5.2.2 on 2025-07-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options_and_more'),
        ('user_panel', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.order'),
            preserve_default=False,
        ),
    ]
