# Generated by Django 5.2.2 on 2025-08-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transaction_order'),
        ('user_panel', '0006_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='user_panel.cart'),
        ),
    ]
