# Generated by Django 5.2.2 on 2025-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='category_ca_status_a5546c_idx'),
        ),
    ]
