# Generated by Django 4.2.23 on 2025-06-28 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت فروش')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='product.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصول فروشنده',
                'verbose_name_plural': 'محصولات فروشندگان',
                'unique_together': {('seller', 'product')},
            },
        ),
    ]
