# Generated by Django 4.2.23 on 2025-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='available_count',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='sell_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
