# Generated by Django 5.2.2 on 2025-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت شده'), (2, 'لغو شده')], default=0),
        ),
    ]
