# Generated by Django 5.2.2 on 2025-08-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_remove_transaction_order_transaction_cart'),
        ('user_panel', '0006_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='seller_product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
