# Generated by Django 5.2.2 on 2025-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0007_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت شده'), (2, 'لغو شده'), (3, 'در حال آماده سازی')], default=0),
        ),
    ]
