# Generated by Django 5.2.2 on 2025-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0008_cart_tracking_code_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='قیمت خریداری شده'),
            preserve_default=False,
        ),
    ]
