# Generated by Django 5.2.2 on 2025-08-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0009_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='قیمت خریداری شده'),
        ),
    ]
