# Generated by Django 5.2.2 on 2025-08-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0010_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerproduct',
            unique_together=set(),
        ),
    ]
