# Generated by Django 5.2.2 on 2025-08-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0011_alter_sellerproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'تایید شده'), (2, 'در حال جمع آوری'), (3, 'تحویل به پست')], default=0),
        ),
    ]
