# Generated by Django 5.2.2 on 2025-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0012_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پرداخت'), (1, 'پرداخت شده'), (2, 'لغو شده'), (3, 'در حال آماده سازی'), (4, 'تحویل به پست')], default=0),
        ),
    ]
