# Generated by Django 5.2.4 on 2025-07-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(max_length=128, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zarin_transactions', to='account.profile')),
            ],
        ),
    ]
